apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: glpi/glpi:11.0.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: glpi-mysql-secret
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: glpi-data
              mountPath: /var/glpi
      volumes:
        - name: glpi-data
          persistentVolumeClaim:
            claimName: glpi-data