apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: glpi
          image: glpi/glpi:latest
          envFrom:
            - secretRef:
                name: glpi-mysql-secret
          volumeMounts:
            - name: glpi-data
              mountPath: /var/glpi
      volumes:
        - name: glpi-data
          persistentVolumeClaim:
            claimName: glpi-data
