apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - glpi-deployment.yaml
  - glpi-service.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - pvc-glpi.yaml
  - pvc-mysql.yaml
  - secrets.yaml
