apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-mysql
  labels:
    app: glpi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi-mysql
  template:
    metadata:
      labels:
        app: glpi-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: glpi-mysql-secret
          ports:
            - name: mysql
              containerPort: 3306
          args:
            - --default-authentication-plugin=mysql_native_password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: glpi-mysql
