
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/project-home-automation.yaml
  - applicationsets/home-automation.yaml
  - projects/project-system-tools.yaml
  - applicationsets/system-tools.yaml
  - projects/project-support.yaml
  - applicationsets/support.yaml
  - projects/project-monitoring.yaml
  - applicationsets/monitoring.yaml
