apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ingress-monitoring.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 65.5.1
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: true
    valuesFile: kube-prometheus-stack-values.yaml

# Note: monitoring Namespace is managed by root-homelab (clusters/homelab/root/namespaces/monitoring.yaml)
