apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - alertmanager-config.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 66.1.1
    releaseName: monitoring
    namespace: monitoring
    valuesFile: kube-prometheus-stack-values.yaml
