
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config-restore-old
  labels:
    app: homeassistant
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 50Gi
