
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwisp-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  tls:
  - hosts: ["openwisp-api.support4u.se"]
    secretName: api-tls
  rules:
  - host: openwisp-api.support4u.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
