
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwisp-controller
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  tls:
  - hosts: ["controller.support4u.se"]
    secretName: controller-tls
  rules:
  - host: controller.support4u.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: controller
            port:
              number: 8000
