apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - nginx-config.yaml
  - nginx-deploy-patch.yaml
  - redis-config.yaml

patches:
  - path: redis-deployment-patch.yaml
    target:
      kind: Deployment
      name: redis
