apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - nginx-config.yaml
  - redis-config.yaml

patches:
  - path: redis-deployment-patch.yaml
    target:
      kind: Deployment
      name: redis

# patchesStrategicMerge converted to JSON6902-style patches
patches:
  - path: nginx-deploy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: openwisp-nginx
      namespace: openwisp