apiVersion: v1
kind: ConfigMap
metadata:
  name: openwisp-nginx-config
  namespace: openwisp
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        client_max_body_size 100M;

        location /static/ {
            alias /static/;
        }

        location /media/ {
            alias /media/;
        }

        location / {
            proxy_pass http://openwisp-controller:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
