apiVersion: v1
kind: ConfigMap
metadata:
  name: openwisp-config
  namespace: openwisp
data:
  TZ: "Europe/Stockholm"
  DASHBOARD_DOMAIN: "openwisp-dashboard.support4u.se"
  API_DOMAIN: "openwisp-api.support4u.se"
  VPN_DOMAIN: "openvpn-openwisp.support4u.se"
  CERT_ADMIN_EMAIL: "admin@support4u.se"
  SSL_CERT_MODE: "External"

  DB_NAME: "openwisp"
  DB_USER: "openwisp"
  DB_HOST: "openwisp-postgres"
  DB_PORT: "5432"
  
  # ðŸ‘‡ LÃ¤gg till dessa rader:
  REDIS_HOST: "openwisp-redis"
  REDIS_PORT: "6379"

  TIMESERIES_DATABASE: |
    {
      "BACKEND": "openwisp_monitoring.db.backends.influxdb",
      "NAME": "openwisp",
      "HOST": "openwisp-influxdb",
      "PORT": "8086",
      "OPTIONS": {
        "udp_writes": false,
        "udp_port": 8089
      }
    }

  INFLUXDB_NAME: "openwisp"
  INFLUXDB_HOST: "openwisp-influxdb"
  INFLUXDB_PORT: "8086"

  USE_OPENWISP_CELERY: "true"
  USE_OPENWISP_FIRMWARE: "false"
  USE_OPENWISP_CELERY_NETWORK: "true"
  USE_OPENWISP_CELERY_FIRMWARE: "false"
  USE_OPENWISP_CELERY_MONITORING: "true"
  OPENWISP_DASHBOARD_URL: "http://openwisp-dashboard"
  CELERY_BROKER_URL: "redis://openwisp-redis:6379/0"

  UWSGI_WORKERS: "2"
  UWSGI_THREADS: "2"