apiVersion: v1
kind: ConfigMap
metadata:
  name: openwisp-env
data:
  DASHBOARD_DOMAIN: "dashboard.support4u.se"
  API_DOMAIN: "api.support4u.se"
  SSH_PRIVATE_KEY_PATH: "/home/openwisp/.ssh/id_ed25519"
  SSH_PUBLIC_KEY_PATH: "/home/openwisp/.ssh/id_ed25519.pub"
  VPN_DOMAIN: "openvpn.support4u.se"
  EMAIL_DJANGO_DEFAULT: "openwisp@support4u.se"
  # DB_USER, DB_PASS, INFLUXDB_USER, INFLUXDB_PASS and DJANGO_SECRET_KEY are in the Secret
  USE_OPENWISP_RADIUS: "True"
  USE_OPENWISP_TOPOLOGY: "True"
  USE_OPENWISP_FIRMWARE: "True"
  USE_OPENWISP_MONITORING: "True"
  UWSGI_PROCESSES: "2"
  UWSGI_THREADS: "2"
  UWSGI_LISTEN: "100"
  SSL_CERT_MODE: "SelfSigned"
  TZ: "Europe/Stockholm"
  CERT_ADMIN_EMAIL: "openwisp-cert@support4u.se"
  DJANGO_LANGUAGE_CODE: "en-gb"
  DB_NAME: "openwisp"
  INFLUXDB_NAME: "openwisp"
  OPENWISP_GEOCODING_CHECK: "True"
  X509_NAME_CA: "default"
  X509_NAME_CERT: "default"
  X509_COUNTRY_CODE: "SE"
  X509_STATE: "Stockholm"
  X509_CITY: "Stockholm"
  X509_ORGANIZATION_NAME: "Support4U"
  X509_ORGANIZATION_UNIT_NAME: "Support4U"
  X509_EMAIL: "certificate@support4u.se"
  X509_COMMON_NAME: "OpenWISP"
  VPN_NAME: "default"
  VPN_CLIENT_NAME: "default-management-vpn"
  DEBUG_MODE: "False"
  DJANGO_LOG_LEVEL: "INFO"
  USE_OPENWISP_CELERY_TASK_ROUTES_DEFAULTS: "True"
  OPENWISP_CELERY_COMMAND_FLAGS: "--concurrency=1"
  USE_OPENWISP_CELERY_NETWORK: "True"
  OPENWISP_CELERY_NETWORK_COMMAND_FLAGS: "--concurrency=1"
  USE_OPENWISP_CELERY_MONITORING: "True"
  OPENWISP_CELERY_MONITORING_COMMAND_FLAGS: "--concurrency=1"
  OPENWISP_CELERY_MONITORING_CHECKS_COMMAND_FLAGS: "--concurrency=1"
  USE_OPENWISP_CELERY_FIRMWARE: "True"
  OPENWISP_CELERY_FIRMWARE_COMMAND_FLAGS: "--concurrency=1"
  METRIC_COLLECTION: "True"
  COLLECTSTATIC_WHEN_DEPS_CHANGE: "true"
