apiVersion: v1
kind: ConfigMap
metadata:
  name: openwisp-config
  namespace: openwisp
data:
  TZ: "Europe/Stockholm"
  DASHBOARD_DOMAIN: "openwisp-desktop.support4u.se"
  API_DOMAIN: "openwisp-api.support4u.se"
  VPN_DOMAIN: "openvpn-openwisp.support4u.se"
  CERT_ADMIN_EMAIL: "admin@support4u.se"
  SSL_CERT_MODE: "External"

  DB_NAME: "openwisp"
  DB_USER: "openwisp"
  DB_HOST: "openwisp-postgres"
  DB_PORT: "5432"

  TIMESERIES_DATABASE: |
    {
      "BACKEND": "openwisp_monitoring.db.backends.influxdb",
      "NAME": "openwisp",
      "HOST": "openwisp-influxdb",
      "PORT": "8086",
      "OPTIONS": {
        "udp_writes": false,
        "udp_port": 8089
      }
    }
