apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwisp-nginx
  template:
    metadata:
      labels:
        app: openwisp-nginx
    spec:
      containers:
      - name: openwisp-nginx
        image: openwisp/openwisp-nginx:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: openwisp-env
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: static
          mountPath: /var/www/openwisp/static
        - name: media
          mountPath: /var/www/openwisp/media
        - name: private
          mountPath: /var/www/openwisp/private
        - name: certs
          mountPath: /etc/letsencrypt
        resources: {}
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: openwisp-static
      - name: media
        persistentVolumeClaim:
          claimName: openwisp-media
      - name: private
        persistentVolumeClaim:
          claimName: openwisp-private-storage
      - name: certs
        persistentVolumeClaim:
          claimName: openwisp-certs
