apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-monitoring
  template:
    metadata:
      labels:
        app: celery-monitoring
    spec:
      containers:
        - name: celery-monitoring
          image: openwisp/openwisp-dashboard:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: openwisp-env
            - secretRef:
                name: openwisp-secrets
          env:
            - name: MODULE_NAME
              value: "celery_monitoring"
          volumeMounts:
            - name: media
              mountPath: /opt/openwisp/media
            - name: private
              mountPath: /opt/openwisp/private
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: openwisp-media
        - name: private
          persistentVolumeClaim:
            claimName: openwisp-private-storage
