apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: openwisp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: openwisp/openwisp-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: openwisp-env
            - secretRef:
                name: openwisp-secrets
          env:
            - name: API_APP_PORT
              value: "8001"
            - name: DB_HOST
              value: "postgres"
            - name: INFLUXDB_HOST
              value: "influxdb"
          ports:
            - containerPort: 8001
              name: http
          volumeMounts:
            - name: media
              mountPath: /opt/openwisp/media
            - name: private
              mountPath: /opt/openwisp/private
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: openwisp-media
        - name: private
          persistentVolumeClaim:
            claimName: openwisp-private-storage
