apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: openwisp/openwisp-dashboard:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: openwisp-env
            - secretRef:
                name: openwisp-secrets
          env:
            - name: MODULE_NAME
              value: "celery"
          volumeMounts:
            - name: media
              mountPath: /opt/openwisp/media
            - name: private
              mountPath: /opt/openwisp/private
            - name: ssh
              mountPath: /home/openwisp/.ssh
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: openwisp-media
        - name: private
          persistentVolumeClaim:
            claimName: openwisp-private-storage
        - name: ssh
          persistentVolumeClaim:
            claimName: openwisp-ssh
