apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwisp-influxdb
  labels:
    app: openwisp-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwisp-influxdb
  template:
    metadata:
      labels:
        app: openwisp-influxdb
    spec:
      containers:
        - name: openwisp-influxdb
          image: influxdb:1.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: INFLUXDB_DB
              value: openwisp
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openwisp-influxdb-data
