apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwisp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboard.support4u.se
        - api.support4u.se
      secretName: openwisp-tls
  rules:
    - host: dashboard.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openwisp-nginx
                port:
                  number: 80
    - host: api.support4u.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openwisp-nginx
                port:
                  number: 80
