apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - endpoints.yaml
  - namespace.yaml
  - ingress.yaml
  - openwisp-openvpn-svc.yaml
  - openwisp-openvpn-endpoints.yaml

