apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard-svc.yaml
  - dashboard-endpoints.yaml
  - api-svc.yaml
  - api-endpoints.yaml
  - openvpn-svc.yaml
  - openvpn-endpoints.yaml
  - ingress.yaml
