apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openwisp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - dashboard.yaml
  - api.yaml
  - celery.yaml
  - celerybeat.yaml
  - websocket.yaml
