apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: home-automation
  labels:
    app: nodered
spec:
  type: ClusterIP
  selector:
    app: nodered
  ports:
    - name: http
      port: 80
      targetPort: 1880
