apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor

resources:
  - snmp-configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - servicemonitor-devices.yaml
