apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - namespace.yaml
  - secret-mariadb.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - redis-secret.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - wordpress-service.yaml
  - wordpress-deployment.yaml
  - ingress.yaml
