apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-nginx
  namespace: wordpress
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      root /var/www/html;
      index index.php index.html;

      client_max_body_size 2048m;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_index index.php;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
      }

      location ~* \.(css|js|jpg|jpeg|png|gif|ico|webp|svg|avif)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
      }
    }
