apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-ini
  namespace: wordpress
data:
  00-custom.ini: |
    memory_limit=512M
    max_execution_time=300
    upload_max_filesize=2048M
    post_max_size=2048M

    opcache.enable=1
    opcache.enable_cli=1
    opcache.memory_consumption=256
    opcache.max_accelerated_files=20000
    opcache.validate_timestamps=1
    opcache.revalidate_freq=2

    ; WordPress behöver normalt inte PHP-sessions. Undvik Redis-sessions här.
